version: "3.8"
services:

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 33307:3306
    volumes:
      - ./Back_End/mysql-db:/var/lib/mysql      

  flask-server:
    build:
      context: ./Back_End/flask-server
      target: base
    ports:
      - '5000:5000'
    # command: bash -c "while true; do sleep 2s; done"
    command: bash -c "uvicorn app.app:app --host 0.0.0.0 --port 5000"
    depends_on:
      - mysql

  react-app:
    stdin_open: true
    tty: true
    build:
      context: ./front_end/ahorrapp
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=PRODUCTION
    ports:
      - '8080:80'

